config/routes.rb
Firstproject::Application.routes.draw do
  resources :games do
    resources :moves
  end
  resources :dungeons do
    resources :rooms
  end
  resources :players

  get "home/index"

   root :to => 'home#index'

end

app/models/dungeon.rb
class Dungeon < ActiveRecord::Base
    attr_accessible :name, :numEnemies, :iorooms
    after_save :generate_rooms
    validates :name,  :presence => true
    validates :numEnemies, :presence => true
    
    has_many :rooms, :dependent => :destroy
    
    def listRooms()
		@rooms.each do |it|
			puts it.name
		end
	end
	
	def getRoom(index)
		room = self.rooms.find(index)
        return room
	end	
    
    private
    def generate_rooms

        @temprooms = JSON.parse(IO.read("vendor/assets/static/dungeon.txt"))
        rnum1 = rand(@temprooms.length - 3) + 2
        rnum2 = rand(@temprooms.length - 3) + 2
        if rnum1 == rnum2
            rnum2 = rnum2 + 1
        end
        
		@temprooms.each_with_index do |r, i|
            if i == rnum1
                room = self.rooms.create(:name => "Exit", :description => "This is the exit!",
            :entrance => "South", :exit =>"North"
            )
            elsif i == rnum2
                room = self.rooms.create(:name => "Minotaur", :description =>"This is the home of the Minotaur!",
            :entrance =>"South",:exit =>"North"
            )
            else
                room = self.rooms.create(:name => "Room_" + 
            r["row"].to_s + "-" + r["col"].to_s, :description =>r["description"],
            :entrance => r["entrance"]["dir"],:exit =>r["exit"]["dir"]
            )
            end
            room.save()
            self.rooms.push(room)
        end
    end
end

app/controllers/dungeons_controller.rb
class DungeonsController < ApplicationController
  # GET /dungeons
  # GET /dungeons.json
  def index
    @dungeons = Dungeon.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @dungeons }
    end
  end

  # GET /dungeons/1
  # GET /dungeons/1.json
  def show
    @dungeon = Dungeon.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @dungeon }
    end
  end

  # GET /dungeons/new
  # GET /dungeons/new.json
  def new
    @dungeon = Dungeon.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @dungeon }
    end
  end

  # GET /dungeons/1/edit
  def edit
    @dungeon = Dungeon.find(params[:id])
  end

  # POST /dungeons
  # POST /dungeons.json
  def create
    @dungeon = Dungeon.new(params[:dungeon])

    respond_to do |format|
      if @dungeon.save
        format.html { redirect_to @dungeon, notice: 'Dungeon was successfully created.' }
        format.json { render json: @dungeon, status: :created, location: @dungeon }
      else
        format.html { render action: "new" }
        format.json { render json: @dungeon.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /dungeons/1
  # PUT /dungeons/1.json
  def update
    @dungeon = Dungeon.find(params[:id])

    respond_to do |format|
      if @dungeon.update_attributes(params[:dungeon])
        format.html { redirect_to @dungeon, notice: 'Dungeon was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @dungeon.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /dungeons/1
  # DELETE /dungeons/1.json
  def destroy
    @dungeon = Dungeon.find(params[:id])
    @dungeon.destroy

    respond_to do |format|
      format.html { redirect_to dungeons_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/dungeons_helper.rb
module DungeonsHelper
end

app/views/dungeons/_form.html.erb
<%= form_for(@dungeon) do |f| %>
  <% if @dungeon.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@dungeon.errors.count, "error") %> prohibited this dungeon from being saved:</h2>

      <ul>
      <% @dungeon.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :numEnemies %><br />
    <%= f.number_field :numEnemies %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/dungeons/edit.html.erb
<h1>Editing dungeon</h1>

<%= render 'form' %>

<%= link_to 'Show', @dungeon %> |
<%= link_to 'Back', dungeons_path %>

app/views/dungeons/index.html.erb
<h1>Listing dungeons</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Numenemies</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @dungeons.each do |dungeon| %>
  <tr>
    <td><%= dungeon.name %></td>
    <td><%= dungeon.numEnemies %></td>
    <td><%= link_to 'Show', dungeon %></td>
    <td><%= link_to 'Edit', edit_dungeon_path(dungeon) %></td>
    <td><%= link_to 'Destroy', dungeon, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Dungeon', new_dungeon_path %>
<%= link_to 'New Game', new_game_path %>

app/views/dungeons/new.html.erb
<h1>New dungeon</h1>

<%= render 'form' %>

<%= link_to 'Back', dungeons_path %>

app/views/dungeons/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @dungeon.name %>
</p>

<p>
  <b>Numenemies:</b>
  <%= @dungeon.numEnemies %>
</p>

<p id="notice"><%= notice %></p>
 
<p>
  <b>Name:</b>
  <%= @dungeon.name %>
</p>

<h2>Rooms</h2>
<%= render @dungeon.rooms %>

<h2>Add a room:</h2>
<%= render "rooms/form" %>

<%= link_to 'Edit', edit_dungeon_path(@dungeon) %> |
<%= link_to 'Back', dungeons_path %>