config/routes.rb
Firstproject::Application.routes.draw do
  resources :games do
    resources :moves
  end
  resources :dungeons do
    resources :rooms
  end
  resources :players

  get "home/index"

   root :to => 'home#index'

end

app/models/move.rb
class Move < ActiveRecord::Base
  attr_accessible :outcome, :direction, :game
  belongs_to :room
  belongs_to :game
  before_save :populateEnemies
  before_save :moveOutcome

  validates :game, :presence => true
  
  def moveOutcome()
    player = Player.find(self.game.player_id)
    dungeon = self.game.dungeon
    if self.game.roomindex == nil        
        room = self.game.dungeon.rooms.first(:order => 'created_at DESC')
        self.game.roomindex = room.id
        self.game.save()
    end
    
    result = player.enter(dungeon.getRoom(self.game.roomindex))
    
    if result[:level] >= 1111
        self.outcome = result[:name]
        self.game.over = true
        self.game.save()

        return
    end
    
    obj = player.move(self)
    if obj.class.to_s == "Fixnum"
        if obj > 1
            return
        end
    else
        self.outcome = obj
        player.enter(dungeon.getRoom(self.game.roomindex))
        self.game.roomindex = self.game.roomindex + 1
        self.outcome += "  Which way would you like to move?"

    end
  end
  
   private
   def populateEnemies()
         if self.game.roomindex == nil        
            room = self.game.dungeon.rooms.first(:order => 'created_at ASC')
            self.game.roomindex = room.id
            self.game.save()
        end
        self.room = self.game.dungeon.getRoom(self.game.roomindex)

        if self.game.dungeon.numEnemies > 0
            self.outcome = ""
            rnum = rand(4)
            directions = [:North, :South, :West, :East]
            if rnum > 2
                e = {:race => ["Dragon", "Goblin","Bandit"][rand(2)], :dungeon => self.game.dungeon,
                :location => room}
                gold = {:name=>"Gold", :level => rand(10)}
                weapon = {:name=>["Sword", "Dagger", "Bow"][rand(2)], :level => 1 + rand(9)}

                armor= {:name=>["Gauntlets","Helmet","Boots"][rand(2)], :level => 1 + rand(9)}

                potion = {:name=>["Healing","Poison","Invisibility"][rand(2)], :level => 1 + rand(9)}

                e[:items] = [gold, weapon, armor, potion]
                self.room.contents.store(directions[rand(4)], e)
            end
            self.game.dungeon.numEnemies = self.game.dungeon.numEnemies - 1
        end
	end  
	 
end

app/controllers/moves_controller.rb
class MovesController < ApplicationController
  def create
    @game = Game.find(params[:game_id])
    @move = @game.moves.create(params[:move])
    redirect_to game_path(@game)
  end
  def destroy
    @game = Game.find(params[:game_id])
    @move = @game.moves.find(params[:move])
    @move.destroy
    redirect_to game_path(@game)
  end
end

app/helpers/moves_helper.rb
module MovesHelper
end

app/views/moves/_form.html.erb
<%= form_for([@game, @game.moves.build]) do |f| %>
  <div class="field">
    <%= f.label :direction %><br />
    <%= f.select :direction, options_for_select([:North, :West, :East, :South]) %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/moves/_move.html.erb
  <p>
    <b>Id:</b>
    <%= move.id %>
    <b>Direction:</b>
    <%= move.direction %>
    <b>Outcome:</b>
    <%= move.outcome %>
    <b>Room:</b>
    <%= render move.room %>
  </p>

app/views/moves/edit.html.erb
<h1>Editing Move</h1>

<%= render 'form' %>

<%= link_to 'Show', @move %> |
<%= link_to 'Back', moves_path %>

app/views/moves/index.html.erb
<h1>Listing Moves</h1>

<table>
  <tr>
    <th>Direction</th>
    <th>Outcome</th>
  </tr>

<% @game.moves.each do |move| %>
  <tr>
    <td><%= move.direction %></td>
    <td><%= move.outcome %></td>
    <td><%= link_to 'Show', move %></td>
    <td><%= link_to 'Destroy', move, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Move', new_move_path %>

app/views/moves/show.html.erb
<p id="notice"><%= notice %></p>

<h2>Moves</h2>
<%= render @move %>

<h2>Add a move:</h2>
<%= render "moves/form" %>

<%= link_to 'Edit', edit_move_path(@game) %> |
<%= link_to 'Back', moves_path %>