config/routes.rb
Firstproject::Application.routes.draw do
  resources :games do
    resources :moves
  end
  resources :dungeons do
    resources :rooms
  end
  resources :players

  get "home/index"

   root :to => 'home#index'

end

app/models/game.rb
class Game < ActiveRecord::Base
  attr_accessor :player
  attr_accessible :player, :player_id, :dungeon, :dungeon_id, :roomindex, :over
  after_save :roomindexSet

  belongs_to :dungeon

  validates :dungeon, :presence => true
  
  has_many :moves, :dependent => :destroy
  
  private
  def roomindexSet
    if self.roomindex == nil && self.over == nil
        room = self.dungeon.rooms.first(:order => 'created_at DESC')
        self.roomindex = room.id
        self.over = false
    end
  end
  
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  # GET /games
  # GET /games.json
  def index
    @games = Game.all
    
    @games.each do |g|
        g.player = Player.find(g.player_id)
    end

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @games }
    end
  end

  # GET /games/1
  # GET /games/1.json
  def show
    @game = Game.find(params[:id])
    @player = Player.find(@game.player_id)
    @moves = @game.moves.find(:all, :order => 'created_at DESC')

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @game }
    end
  end

  # GET /games/new
  # GET /games/new.json
  def new
    @game = Game.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @game }
    end
  end

  # GET /games/1/edit
  def edit
    @game = Game.find(params[:id])
  end

  # POST /games
  # POST /games.json
  def create
    @game = Game.new(params[:game])

    respond_to do |format|
      if @game.save
        format.html { redirect_to @game, notice: 'Game was successfully created.' }
        format.json { render json: @game, status: :created, location: @game }
      else
        format.html { render action: "new" }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /games/1
  # PUT /games/1.json
  def update
    @game = Game.find(params[:id])

    respond_to do |format|
      if @game.update_attributes(params[:game])
        format.html { redirect_to @game, notice: 'Game was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /games/1
  # DELETE /games/1.json
  def destroy
    @game = Game.find(params[:id])
    @game.destroy

    respond_to do |format|
      format.html { redirect_to games_url }
      format.json { head :no_content }
    end
  end

end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/games/_form.html.erb
<%= form_for @game do |f| %>
  <% if @game.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@game.errors.count, "error") %> prohibited this game from being saved:</h2>

      <ul>
      <% @game.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.collection_select :player_id, Player.all, :id, :name, :prompt => true -%><br />
    <%= f.collection_select :dungeon_id, Dungeon.all, :id, :name, :prompt => true -%>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/games/edit.html.erb
<h1>Editing game</h1>

<%= render 'form' %>



<%= link_to 'Show', @game %> |
<%= link_to 'Back', games_path %>

app/views/games/index.html.erb
<h1>Listing Games</h1>

<table>
  <tr>
    <th>Player</th>
    <th>Dungeon</th>

  </tr>

<% @games.each do |game| %>
  <tr>
    <td><%= render game.player %></td>
    <td><%= game.dungeon.name %></td>
    <td><%= link_to 'Show', game %></td>
    <td><%= link_to 'Destroy', game, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Game', new_game_path %>

app/views/games/new.html.erb
<h1>New Game</h1>

<%= render 'form' %>

<%= link_to 'New Dungeon', new_dungeon_path %>
<%= link_to 'Back', games_path %>

app/views/games/show.html.erb
<p id="notice"><%= notice %></p>

<p>
<b>Player:</b>
  <%= render @player %><br />
  <b>Dungeon:</b>
  <%= @game.dungeon.name %><br />
  <% if @game.over? %>
<h2>Game Over!</h2>
<%= link_to 'New Game', new_game_path %>
<%= link_to 'Back', games_path %>
<% else %>
  <b>Roomindex:</b>
  <%= @game.roomindex %>

</p>


<p id="notice"><%= notice %></p>
<h2>Add a move:</h2>
<%= render "moves/form" %>
<% end %>

<h2>Moves</h2>
<%= render @moves %>



<%= link_to 'Edit', edit_game_path(@game) %> |
<%= link_to 'Back', games_path %>